# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartegories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartegory_name', models.CharField(max_length=150)),
                ('cartegory_logo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.CharField(max_length=4)),
                ('cart', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodduct_name', models.CharField(max_length=150)),
                ('product_picture', models.CharField(max_length=250)),
                ('product_description', models.CharField(max_length=550)),
                ('product_cost', models.CharField(max_length=250)),
                ('cartegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Cartegories')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products'),
        ),
    ]
