# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171127_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='prodduct_name',
            new_name='product_name',
        ),
    ]
