# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20171127_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='products',
        ),
        migrations.AddField(
            model_name='products',
            name='cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
