# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20171127_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_picture',
        ),
    ]
