# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_products_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='cartegory',
        ),
        migrations.DeleteModel(
            name='Cartegories',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
