# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_auto_20171127_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartegories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('category_logo', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_logo', models.FileField(upload_to=b'')),
                ('product_field', models.CharField(max_length=150)),
                ('product_details', models.CharField(max_length=750)),
                ('product_cost', models.CharField(max_length=20)),
                ('favorite', models.BooleanField(default=False)),
                ('cart', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Cartegories')),
            ],
        ),
    ]
