# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_cartegories_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartegories',
            old_name='category_logo',
            new_name='cartegory_logo',
        ),
        migrations.RenameField(
            model_name='cartegories',
            old_name='category_name',
            new_name='cartegory_name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='cartegory',
        ),
    ]
