# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20171217_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='county',
        ),
        migrations.AlterField(
            model_name='adress',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Town'),
        ),
    ]
